// Code generated by hertz generator.

package main

import (
	dao "dy/biz/db"

	cache "dy/biz/cache"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzzap "github.com/hertz-contrib/logger/zap"
)

func ConfigLog() {
	logger := hertzzap.NewLogger(
		hertzzap.WithZapOptions(
		// ...
		),
	)
	hlog.SetLogger(logger)
}
func Init() {
	dao.Init()
	cache.Init()
	ConfigLog()
}
func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8001"))
	Init()
	register(h)
	h.Spin()
}
